Modify ci

diff --git a/.gitlab-ci.yml b/.gitlab-ci.yml
--- a/.gitlab-ci.yml
+++ b/.gitlab-ci.yml
@@ -2,23 +2,15 @@ image: alpine:latest
 
 variables:
   LM_JAVA_VERSION: 11
+  DOCKER_REGISTRY: 574283098123.dkr.ecr.us-west-2.amazonaws.com/obb-conformance-suite
 
 stages:
   - build
   - upload
-  - deploy
-  - test
-  - compare
-  - cleanup
-
-# These are disabled because they fail with warnings, stopping pipelines being green, and we don't get a huge
-# amount of value from them (the security license scanning is done by github on the mirror of the project, so
-# we don't lose anything - and in fact it works better on github).
-# https://gitlab.com/gitlab-org/gitlab/-/issues/220275 is one of the issues causing warnings, but it seems like
-# another similar issue has been added to license scanning since
-#include:
-#  - template: Security/Dependency-Scanning.gitlab-ci.yml
-#  - template: Security/License-Scanning.gitlab-ci.yml
+#  - deploy
+#  - test
+#  - compare
+#  - cleanup
 
 .maven: &maven
   image: maven:3-jdk-11
@@ -35,13 +27,14 @@ build:
   <<: *maven
   stage: build
   script:
-    # Don't compile the tests yet
-    - mvn -B -Dmaven.test.skip -Dpmd.skip clean package
+    - mvn -B -Dpmd.skip clean package
   artifacts:
     paths:
       - target/
 
 upload:
+  rules:
+    - if: $CI_COMMIT_BRANCH == "master"
   stage: upload
   interruptible: true
   needs: ["build"]
@@ -58,52 +51,52 @@ upload:
   allow_failure:
     exit_codes:
       - 137
-
-test:
-  <<: *maven
-  stage: test
-  needs: ["build"]
-  script:
-    # Don't recompile the main app
-    - mvn -B -Dmaven.main.skip test
-    - |
-      perl -ne '/Total.*?(\d+%)/ && print "Unit test coverage $1\n"' target/site/jacoco/index.html
-  only:
-    - branches
-
-.compare: &compare
-  stage: compare
-  interruptible: true
-  # we only want to show a 'warning' if there's differences, but gitlab is inflexible so any failure will show as a
-  # warning. When implemented, https://gitlab.com/gitlab-org/gitlab/-/issues/16733 would allow us to still fail if
-  # something went wrong.
-  allow_failure: true
-  image: python:alpine
-  only:
-    refs:
-      - branches
-    kubernetes: active
-
-compare_cloud:
-  <<: *compare
-  needs: ["server_test", "ciba_test", "client_test"]
-  script:
-    - run_compare server_test ciba_test client_test
-
-compare_local:
-  <<: *compare
-  needs: ["local_test"]
-  script:
-    - run_compare local_test
-
-check-trailing-whitespace:
-  interruptible: true
-  stage: build
-  image: python:2
-  script:
-    - ./scripts/checkwhitespace.py
-  only:
-    - branches
+#
+#test:
+#  <<: *maven
+#  stage: test
+#  needs: ["build"]
+#  script:
+#    # Don't recompile the main app
+#    - mvn -B -Dmaven.main.skip test
+#    - |
+#      perl -ne '/Total.*?(\d+%)/ && print "Unit test coverage $1\n"' target/site/jacoco/index.html
+#  only:
+#    - branches
+#
+#.compare: &compare
+#  stage: compare
+#  interruptible: true
+#  # we only want to show a 'warning' if there's differences, but gitlab is inflexible so any failure will show as a
+#  # warning. When implemented, https://gitlab.com/gitlab-org/gitlab/-/issues/16733 would allow us to still fail if
+#  # something went wrong.
+#  allow_failure: true
+#  image: python:alpine
+#  only:
+#    refs:
+#      - branches
+#    kubernetes: active
+#
+#compare_cloud:
+#  <<: *compare
+#  needs: ["server_test", "ciba_test", "client_test"]
+#  script:
+#    - run_compare server_test ciba_test client_test
+#
+#compare_local:
+#  <<: *compare
+#  needs: ["local_test"]
+#  script:
+#    - run_compare local_test
+#
+#check-trailing-whitespace:
+#  interruptible: true
+#  stage: build
+#  image: python:2
+#  script:
+#    - ./scripts/checkwhitespace.py
+#  only:
+#    - branches
 
 #codequality:
 #  image: docker:latest
@@ -116,160 +109,160 @@ check-trailing-whitespace:
 #    - codeclimate
 #  artifacts:
 #    paths: [codeclimate.json]
-
-.auto-deploy:
-  image: "registry.gitlab.com/gitlab-org/cluster-integration/auto-deploy-image:v1.1.0"
-
-.deploy: &deploy
-  extends: .auto-deploy
-  stage: deploy
-  # there's a race condition between 'find_deploy_url' and the actual deploy where we could end up with multiple
-  # deployments to the same url - use a resource_group to avoid multiple deploy jobs running at the same time
-  resource_group: deploy
-  script:
-    - find_deploy_url
-    - echo "DYNAMIC_ENVIRONMENT_URL=$CI_ENVIRONMENT_URL" >> deploy.env
-    - auto-deploy check_kube_domain
-    - auto-deploy download_chart
-    - auto-deploy ensure_namespace
-    - auto-deploy initialize_tiller
-    - deploy
-  artifacts:
-    reports:
-      dotenv: deploy.env
-  dependencies: []
-  only:
-    refs:
-      - branches
-    kubernetes: active
-
-deploy-review:
-  <<: *deploy
-  environment:
-    name: review/$CI_COMMIT_REF_NAME
-    on_stop: stop_review
-    url: $DYNAMIC_ENVIRONMENT_URL
-  except:
-    - master
-    - production
-    - demo
-
-deploy-normal:
-  <<: *deploy
-  environment:
-    name: $CI_COMMIT_BRANCH
-    on_stop: stop_normal
-    url: $DYNAMIC_ENVIRONMENT_URL
-  only:
-    - production
-    - demo
-
-deploy-staging:
-  <<: *deploy
-  environment:
-    name: staging
-    url: $DYNAMIC_ENVIRONMENT_URL
-  only:
-    - master
-
-stop_review:
-  extends: .auto-deploy
-  stage: cleanup
-  variables:
-    GIT_STRATEGY: none
-  script:
-    - auto-deploy initialize_tiller
-    - auto-deploy delete
-  environment:
-    name: review/$CI_COMMIT_REF_NAME
-    action: stop
-  needs: []
-  when: manual
-  allow_failure: true
-  only:
-    refs:
-      - branches
-    kubernetes: active
-  except:
-    - master
-    - production
-    - demo
-
-stop_normal:
-  extends: .auto-deploy
-  stage: cleanup
-  variables:
-    GIT_STRATEGY: none
-  script:
-    - auto-deploy initialize_tiller
-    - auto-deploy delete
-  environment:
-    name: $CI_COMMIT_BRANCH
-    action: stop
-  needs: []
-  when: manual
-  allow_failure: true
-  only:
-    - demo
-
-.deployment_test: &deployment_test
-  stage: test
-  interruptible: true
-  image: python:alpine
-  only:
-    refs:
-      - branches
-    kubernetes: active
-  artifacts:
-    when: always
-    paths:
-      - "*.zip"
-
-client_test:
-  <<: *deployment_test
-  script:
-    - set_up_for_running_test_plan
-    - run_client_test_plan
-
-server_test:
-  <<: *deployment_test
-  script:
-    - set_up_for_running_test_plan
-    - run_server_test_plan
-
-ciba_test:
-  <<: *deployment_test
-  script:
-    - set_up_for_running_test_plan
-    - run_ciba_test_plan
-
-local_test:
-  stage: test
-  interruptible: true
-  image: docker:19.03.10
-  services:
-    - docker:dind
-  needs: ["build"]
-  script:
-    - apk add docker-compose
-    - docker-compose -f $CI_PROJECT_DIR/docker-compose-localtest.yml pull
-    - docker-compose -f $CI_PROJECT_DIR/docker-compose-localtest.yml build --pull
-    - docker-compose -f $CI_PROJECT_DIR/docker-compose-localtest.yml up --detach httpd
-    - sleep 5
-    - docker-compose -f $CI_PROJECT_DIR/docker-compose-localtest.yml logs --tail="all" oidcc-provider
-    - docker-compose -f $CI_PROJECT_DIR/docker-compose-localtest.yml run test
-  after_script:
-    - docker-compose -f $CI_PROJECT_DIR/docker-compose-localtest.yml logs --tail="all" oidcc-provider > $CI_PROJECT_DIR/oidcc-provider-log.txt
-    - docker-compose -f $CI_PROJECT_DIR/docker-compose-localtest.yml logs --tail="all" server > $CI_PROJECT_DIR/server-log.txt
-    - docker-compose -f $CI_PROJECT_DIR/docker-compose-localtest.yml exec -T mongodb mongodump --db=test_suite --archive=/data/db/mongodb-dump.gz --gzip
-    - docker-compose -f $CI_PROJECT_DIR/docker-compose-localtest.yml down
-  artifacts:
-    when: always
-    paths:
-      - oidcc-provider-log.txt
-      - server-log.txt
-      - mongo/data/mongodb-dump.gz
-      - "*.zip"
+#
+#.auto-deploy:
+#  image: "registry.gitlab.com/gitlab-org/cluster-integration/auto-deploy-image:v1.1.0"
+#
+#.deploy: &deploy
+#  extends: .auto-deploy
+#  stage: deploy
+#  # there's a race condition between 'find_deploy_url' and the actual deploy where we could end up with multiple
+#  # deployments to the same url - use a resource_group to avoid multiple deploy jobs running at the same time
+#  resource_group: deploy
+#  script:
+#    - find_deploy_url
+#    - echo "DYNAMIC_ENVIRONMENT_URL=$CI_ENVIRONMENT_URL" >> deploy.env
+#    - auto-deploy check_kube_domain
+#    - auto-deploy download_chart
+#    - auto-deploy ensure_namespace
+#    - auto-deploy initialize_tiller
+#    - deploy
+#  artifacts:
+#    reports:
+#      dotenv: deploy.env
+#  dependencies: []
+#  only:
+#    refs:
+#      - branches
+#    kubernetes: active
+#
+#deploy-review:
+#  <<: *deploy
+#  environment:
+#    name: review/$CI_COMMIT_REF_NAME
+#    on_stop: stop_review
+#    url: $DYNAMIC_ENVIRONMENT_URL
+#  except:
+#    - master
+#    - production
+#    - demo
+#
+#deploy-normal:
+#  <<: *deploy
+#  environment:
+#    name: $CI_COMMIT_BRANCH
+#    on_stop: stop_normal
+#    url: $DYNAMIC_ENVIRONMENT_URL
+#  only:
+#    - production
+#    - demo
+#
+#deploy-staging:
+#  <<: *deploy
+#  environment:
+#    name: staging
+#    url: $DYNAMIC_ENVIRONMENT_URL
+#  only:
+#    - master
+#
+#stop_review:
+#  extends: .auto-deploy
+#  stage: cleanup
+#  variables:
+#    GIT_STRATEGY: none
+#  script:
+#    - auto-deploy initialize_tiller
+#    - auto-deploy delete
+#  environment:
+#    name: review/$CI_COMMIT_REF_NAME
+#    action: stop
+#  needs: []
+#  when: manual
+#  allow_failure: true
+#  only:
+#    refs:
+#      - branches
+#    kubernetes: active
+#  except:
+#    - master
+#    - production
+#    - demo
+#
+#stop_normal:
+#  extends: .auto-deploy
+#  stage: cleanup
+#  variables:
+#    GIT_STRATEGY: none
+#  script:
+#    - auto-deploy initialize_tiller
+#    - auto-deploy delete
+#  environment:
+#    name: $CI_COMMIT_BRANCH
+#    action: stop
+#  needs: []
+#  when: manual
+#  allow_failure: true
+#  only:
+#    - demo
+#
+#.deployment_test: &deployment_test
+#  stage: test
+#  interruptible: true
+#  image: python:alpine
+#  only:
+#    refs:
+#      - branches
+#    kubernetes: active
+#  artifacts:
+#    when: always
+#    paths:
+#      - "*.zip"
+#
+#client_test:
+#  <<: *deployment_test
+#  script:
+#    - set_up_for_running_test_plan
+#    - run_client_test_plan
+#
+#server_test:
+#  <<: *deployment_test
+#  script:
+#    - set_up_for_running_test_plan
+#    - run_server_test_plan
+#
+#ciba_test:
+#  <<: *deployment_test
+#  script:
+#    - set_up_for_running_test_plan
+#    - run_ciba_test_plan
+#
+#local_test:
+#  stage: test
+#  interruptible: true
+#  image: docker:19.03.10
+#  services:
+#    - docker:dind
+#  needs: ["build"]
+#  script:
+#    - apk add docker-compose
+#    - docker-compose -f $CI_PROJECT_DIR/docker-compose-localtest.yml pull
+#    - docker-compose -f $CI_PROJECT_DIR/docker-compose-localtest.yml build --pull
+#    - docker-compose -f $CI_PROJECT_DIR/docker-compose-localtest.yml up --detach httpd
+#    - sleep 5
+#    - docker-compose -f $CI_PROJECT_DIR/docker-compose-localtest.yml logs --tail="all" oidcc-provider
+#    - docker-compose -f $CI_PROJECT_DIR/docker-compose-localtest.yml run test
+#  after_script:
+#    - docker-compose -f $CI_PROJECT_DIR/docker-compose-localtest.yml logs --tail="all" oidcc-provider > $CI_PROJECT_DIR/oidcc-provider-log.txt
+#    - docker-compose -f $CI_PROJECT_DIR/docker-compose-localtest.yml logs --tail="all" server > $CI_PROJECT_DIR/server-log.txt
+#    - docker-compose -f $CI_PROJECT_DIR/docker-compose-localtest.yml exec -T mongodb mongodump --db=test_suite --archive=/data/db/mongodb-dump.gz --gzip
+#    - docker-compose -f $CI_PROJECT_DIR/docker-compose-localtest.yml down
+#  artifacts:
+#    when: always
+#    paths:
+#      - oidcc-provider-log.txt
+#      - server-log.txt
+#      - mongo/data/mongodb-dump.gz
+#      - "*.zip"
 
 # ---------------------------------------------------------------------------
 
@@ -471,12 +464,8 @@ local_test:
   function install_build_dependencies() {
     apk -q add --no-cache --update --upgrade curl tar gzip make ca-certificates openssl python3 py-pip
     update-ca-certificates
-    pip -q install docker-compose==1.23.2
+    pip3 -q install docker-compose==1.23.2 awscli==1.19.76
     docker-compose --version
-
-    curl https://dl.google.com/dl/cloudsdk/release/google-cloud-sdk.tar.gz | tar zx
-    ./google-cloud-sdk/install.sh --usage-reporting=false --path-update=true
-    ./google-cloud-sdk/bin/gcloud --quiet components update
   }
 
   function run_compare() {
@@ -493,25 +482,22 @@ local_test:
   }
 
   function upload() {
-    if [ -z "$GCP_PROJECT_ID" ]; then
-      echo "No GCP integration configured - the full set of tests cannot be run."
-      echo ""
-      echo "If this is a merge request being submitted to"
-      echo "https://gitlab.com/openid/conformance-suite"
-      echo "an OIDF developer will review the code and then create a new pipeline"
-      echo "to run the full set of tests."
-      exit 137 # this will show as a warning in the pipeline, see allow_failure: entry
+    if [ -z "$AWS_ACCESS_KEY_ID" ] || [ -z "$AWS_SECRET_ACCESS_KEY" ]; then
+      echo "No AWS access credentials configured - cannot push image"
+      exit 138
     fi
 
-    docker tag conformance-suite "$CI_APPLICATION_REPOSITORY:$CI_APPLICATION_TAG"
+    docker tag conformance-suite "$DOCKER_REGISTRY:$CI_APPLICATION_TAG"
+    docker tag conformance-suite "$DOCKER_REGISTRY:sandbox"
 
     echo "Logging in to container registry..."
-    echo "$GCLOUD_SERVICE_KEY" | base64 -d > ${HOME}/gcloud-service-key.json
-    ./google-cloud-sdk/bin/gcloud auth activate-service-account --key-file ${HOME}/gcloud-service-key.json
 
-    echo "Pushing to GCR..."
-    ./google-cloud-sdk/bin/gcloud docker -- push "$CI_APPLICATION_REPOSITORY:$CI_APPLICATION_TAG"
-    echo ""
+    aws ecr --region us-west-2 get-login-password | docker login --username AWS --password-stdin $DOCKER_REGISTRY
+
+    echo "Pusing image to ECR"
+    docker push $DOCKER_REGISTRY:$CI_APPLICATION_TAG
+    docker push $DOCKER_REGISTRY:sandbox
+
   }
 
   function install_test_dependencies() {
@@ -521,8 +507,6 @@ local_test:
     eval $(ssh-agent -s)
     echo "$SSH_PRIVATE_KEY" | ssh-add -
     cd ..
-    GIT_SSH_COMMAND="ssh -o StrictHostKeyChecking=no" git clone git@gitlab.com:openid/conformance-suite-private.git
-    cd conformance-suite-private
   }
 
   function set_up_for_running_test_plan() {
